---
- name: Network Scan and Report
  hosts: localhost
  gather_facts: no

  vars:
    network_range: "192.168.1.0/24"
    output_file: "network_scan_report.csv"
    ssh_timeout: 10

  tasks:
    - name: Scan network for ICMP ping and SSH port (22)
      ansible.builtin.raw: "nmap -sn -PS -p 22 --open -oG - {{ network_range }}"
      register: nmap_output

    - name: Generate report
      ansible.builtin.file:
        path: "{{ output_file }}"
        state: touch

    - name: Write headers to the report
      ansible.builtin.lineinfile:
        path: "{{ output_file }}"
        line: "IP Address,Hostname,Ping,SSH"

    - name: Loop through scan results
      ansible.builtin.block:
        - name: Parse nmap output
          ansible.builtin.set_fact:
            scan_results: "{{ nmap_output.stdout_lines | select('match', '^Host:\\s*(.*)\\s*\\((.*)\\)\\s*Status:\\s*(.*)$') | map('regex_replace', '^Host:\\s*(.*)\\s*\\((.*)\\)\\s*Status:\\s*(.*)$', '\\1,\\2,\\3') | list }}"

        - name: Wait for ping response
          ansible.builtin.wait_for:
            host: "{{ item.split(',')[1] }}"
            state: started
            delay: 5
            timeout: "{{ ssh_timeout }}"
          loop: "{{ scan_results }}"

        - name: Get hostname via SSH
          ansible.builtin.expect:
            command: ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null user@{{ item.split(',')[1] }} hostname
            responses:
              'assword': "{{ ssh_password }}"
          delegate_to: localhost
          register: hostname_output
          changed_when: false
          failed_when: false
          loop: "{{ scan_results }}"
          vars:
            ssh_password: "your_ssh_password"  # You may need to provide SSH password or use SSH keys

        - name: Write scan results to the report
          ansible.builtin.lineinfile:
            path: "{{ output_file }}"
            line: "{{ item.split(',')[1] }},{{ item.split(',')[0] }},{{ 'Success' if item.split(',')[2] == 'Up' else 'Failure' }},{{ 'Success' if 'ssh' in item.split(',')[3] else 'Failure' }}"
          loop: "{{ hostname_output.results }}"
