---
- name: Network Scan and Report
  hosts: localhost
  gather_facts: no

  vars:
    network_range: "192.168.1.0/24"
    output_file: "network_scan_report.csv"
    ssh_timeout: 10

  tasks:
    - name: Scan network and gather facts
      nmap:
        targets: "{{ network_range }}"
        ports: "22"
        tasks:
          - name: ssh
            service: "ssh"
      register: scan_result

    - name: Generate report
      ansible.builtin.file:
        path: "{{ output_file }}"
        state: touch

    - name: Write headers to the report
      ansible.builtin.lineinfile:
        path: "{{ output_file }}"
        line: "IP Address,Hostname,Ping,SSH"

    - name: Loop through scan results
      ansible.builtin.block:
        - name: Wait for SSH port to be open
          ansible.builtin.wait_for:
            host: "{{ item.item }}"
            port: 22
            state: started
            delay: 5
            timeout: "{{ ssh_timeout }}"
          loop: "{{ scan_result.scan }}"

        - name: Get hostname via SSH
          ansible.builtin.expect:
            command: ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null user@{{ item.item }} hostname
            responses:
              'assword': "{{ ssh_password }}"
          delegate_to: localhost
          register: hostname_output
          changed_when: false
          failed_when: false
          loop: "{{ scan_result.scan }}"
          vars:
            ssh_password: "your_ssh_password"  # You may need to provide SSH password or use SSH keys

        - name: Write scan results to the report
          ansible.builtin.lineinfile:
            path: "{{ output_file }}"
            line: "{{ item.item }},{{ item.stdout_lines[0] if item.rc == 0 else 'N/A' }},{{ 'Success' if 'ssh' in item.item.ports_results else 'Failure' }},{{ item.stdout_lines[0] if item.rc == 0 else 'N/A' }}"
          loop: "{{ hostname_output.results }}"
